export const quizData = [
    // Easy Questions
    {
      question: "Sino ang pambansang bayani ng Pilipinas?",
      options: ["Andres Bonifacio", "Emilio Aguinaldo", "Jose Rizal", "Apolinario Mabini"],
      answer: "Jose Rizal",
      difficulty: "easy",
    },
    {
      question: "Sino ang unang babaeng pangulo ng Pilipinas?",
      options: ["Corazon Aquino", "Gloria Macapagal-Arroyo", "Imelda Marcos", "Leni Robredo"],
      answer: "Corazon Aquino",
      difficulty: "easy",
    },
    {
      question: "Ano ang tawag sa pinakaunang alpabetong Filipino?",
      options: ["Baybayin", "Abakada", "Alibata", "Latin Alphabet"],
      answer: "Baybayin",
      difficulty: "easy",
    },
    {
      question: "Saan matatagpuan ang Banaue Rice Terraces?",
      options: ["Ifugao", "Benguet", "Mountain Province", "Kalinga"],
      answer: "Ifugao",
      difficulty: "easy",
    },
    {
      question: "Ano ang pangalan ng pambansang ibon ng Pilipinas?",
      options: ["Agila", "Maya", "Tamaraw", "Philippine Eagle"],
      answer: "Philippine Eagle",
      difficulty: "easy",
    },
    {
      question: "Ano ang pambansang kasuotan ng mga lalaki sa Pilipinas?",
      options: ["Barong Tagalog", "Baro't Saya", "Kamiseta", "Kimona"],
      answer: "Barong Tagalog",
      difficulty: "easy",
    },
    {
      question: "Sino ang pangunahing tauhan sa El Filibusterismo?",
      options: ["Simoun", "Ibarra", "Basilio", "Crisostomo"],
      answer: "Simoun",
      difficulty: "easy",
    },
    {
      question: "Saan matatagpuan ang Chocolate Hills?",
      options: ["Bohol", "Cebu", "Palawan", "Davao"],
      answer: "Bohol",
      difficulty: "easy",
    },
    {
      question: "Ano ang simbolo ng walong sinag ng araw sa watawat ng Pilipinas?",
      options: ["Walong lalawigan", "Walong isla", "Walong bayani", "Walong bayan"],
      answer: "Walong lalawigan",
      difficulty: "easy",
    },
    {
      question: "Sino ang kilalang ‘Dakilang Lumpo’?",
      options: ["Apolinario Mabini", "Jose Rizal", "Andres Bonifacio", "Antonio Luna"],
      answer: "Apolinario Mabini",
      difficulty: "easy",
    },
    {
      question: "Anong probinsya ang kilala sa MassKara Festival?",
      options: ["Negros Occidental", "Cebu", "Iloilo", "Davao"],
      answer: "Negros Occidental",
      difficulty: "easy",
    },
    {
      question: "Ano ang pinakamatandang simbahan sa Pilipinas?",
      options: ["San Agustin Church", "Quiapo Church", "Manila Cathedral", "Basilica del Santo Niño"],
      answer: "San Agustin Church",
      difficulty: "easy",
    },
    {
      question: "Ano ang pangalan ng pinakamahabang ilog sa Pilipinas?",
      options: ["Cagayan River", "Agusan River", "Pasig River", "Pampanga River"],
      answer: "Cagayan River",
      difficulty: "easy",
    },
    {
      question: "Sino ang Ama ng Wikang Pambansa?",
      options: ["Manuel L. Quezon", "Jose Rizal", "Emilio Aguinaldo", "Andres Bonifacio"],
      answer: "Manuel L. Quezon",
      difficulty: "easy",
    },
    {
      question: "Anong lungsod ang tinaguriang 'Summer Capital of the Philippines'?",
      options: ["Baguio", "Tagaytay", "Davao", "Cebu"],
      answer: "Baguio",
      difficulty: "easy",
    },
    {
      question: "Saan naganap ang 'Battle of Mactan'?",
      options: ["Mactan", "Cebu", "Bohol", "Leyte"],
      answer: "Mactan",
      difficulty: "easy",
    },
    {
      question: "Anong bayan ang kilala bilang 'City of Love'?",
      options: ["Iloilo City", "Tagaytay", "Cebu City", "Manila"],
      answer: "Iloilo City",
      difficulty: "easy",
    },
    {
      question: "Ano ang unang pangalan ng Lungsod ng Maynila?",
      options: ["Maynilad", "Tondo", "Intramuros", "Taguig"],
      answer: "Maynilad",
      difficulty: "easy",
    },
    {
      question: "Saan matatagpuan ang Mount Mayon?",
      options: ["Albay", "Laguna", "Cebu", "Benguet"],
      answer: "Albay",
      difficulty: "easy",
    },
    {
      question: "Ano ang sagisag ng tatlong bituin sa watawat ng Pilipinas?",
      options: ["Luzon, Visayas, Mindanao", "Tatlong bayani", "Tatlong bansa", "Tatlong bayan"],
      answer: "Luzon, Visayas, Mindanao",
      difficulty: "easy",
    },
    {
      question: "Saan matatagpuan ang Tubbataha Reef?",
      options: ["Palawan", "Cebu", "Leyte", "Davao"],
      answer: "Palawan",
      difficulty: "easy",
    },
    {
      question: "Sino ang unang babaeng senador ng Pilipinas?",
      options: ["Geronima Pecson", "Corazon Aquino", "Gloria Macapagal-Arroyo", "Miriam Defensor Santiago"],
      answer: "Geronima Pecson",
      difficulty: "easy",
    },
    {
      question: "Sino ang Pangulo ng Pilipinas noong World War II?",
      options: ["Jose P. Laurel", "Manuel L. Quezon", "Sergio Osmeña", "Emilio Aguinaldo"],
      answer: "Jose P. Laurel",
      difficulty: "easy",
    },
    {
      question: "Ano ang tradisyonal na sasakyang Pilipino na ginagamit sa tubig?",
      options: ["Bangka", "Karwahe", "Traysikel", "Jeepney"],
      answer: "Bangka",
      difficulty: "easy",
    },
    {
      question: "Anong isla ang may Chocolate Hills?",
      options: ["Bohol", "Palawan", "Negros", "Leyte"],
      answer: "Bohol",
      difficulty: "easy",
    },
    {
      question: "Ano ang pambansang laro ng Pilipinas?",
      options: ["Arnis", "Basketball", "Sepak Takraw", "Sipa"],
      answer: "Arnis",
      difficulty: "easy",
    },
    {
      question: "Ano ang pangalan ng unang pambansang barko ng Pilipinas?",
      options: ["BRP Datu Kalantiaw", "BRP Rizal", "BRP Gabriela Silang", "BRP Jose Rizal"],
      answer: "BRP Gabriela Silang",
      difficulty: "easy",
    },
    {
      question: "Anong materyales ang ginagamit sa paggawa ng bahay kubo?",
      options: ["Kawayan at Nipa", "Semento at Buhangin", "Kahoy at Yero", "Metal at Plastik"],
      answer: "Kawayan at Nipa",
      difficulty: "easy",
    },
    {
      question: "Ano ang sinisimbolo ng Sampaguita sa kultura ng Pilipino?",
      options: ["Kalinisang-Puri", "Katapangan", "Kagandahan", "Kasipagan"],
      answer: "Kalinisang-Puri",
      difficulty: "easy",
    },
    {
      question: "Anong lungsod ang kilala bilang 'City of Pines'?",
      options: ["Baguio", "Tagaytay", "Cebu", "Manila"],
      answer: "Baguio",
      difficulty: "easy",
    },
    {
      question: "Ano ang kilalang produkto ng Bicol Region?",
      options: ["Laing", "Durian", "Mango", "Coconut"],
      answer: "Laing",
      difficulty: "easy",
    },
    {
      question: "Anong taon ipinanganak si Jose Rizal?",
      options: ["1861", "1865", "1863", "1870"],
      answer: "1861",
      difficulty: "easy",
    },
    {
      question: "Saan ipinanganak si Andres Bonifacio?",
      options: ["Cavite", "Manila", "Laguna", "Batangas"],
      answer: "Cavite",
      difficulty: "easy",
    },
    {
      question: "Anong pangalan ng unang pangulo ng Pilipinas?",
      options: ["Emilio Aguinaldo", "Sergio Osmeña", "Manuel L. Quezon", "Ferdinand Marcos"],
      answer: "Emilio Aguinaldo",
      difficulty: "easy",
    },
    {
      question: "Anong taon ipinanganak si Andres Bonifacio?",
      options: ["1863", "1860", "1870", "1855"],
      answer: "1863",
      difficulty: "easy",
    },
    {
      question: "Sino ang nagdeklara ng kalayaan ng Pilipinas noong 1898?",
      options: ["Emilio Aguinaldo", "Jose Rizal", "Andres Bonifacio", "Ferdinand Marcos"],
      answer: "Emilio Aguinaldo",
      difficulty: "easy",
    },
    {
      question: "Anong taon ipinanganak si Ferdinand Marcos?",
      options: ["1917", "1925", "1910", "1900"],
      answer: "1917",
      difficulty: "easy",
    },
    {
      question: "Sino ang nagpasimula ng Katipunan?",
      options: ["Jose Rizal", "Andres Bonifacio", "Emilio Aguinaldo", "Apolinario Mabini"],
      answer: "Andres Bonifacio",
      difficulty: "easy",
    },
    {
      question: "Anong taon nilusob ang Intramuros?",
      options: ["1945", "1941", "1939", "1914"],
      answer: "1945",
      difficulty: "easy",
    },
    {
      question: "Saan matatagpuan ang Luneta Park?",
      options: ["Quezon City", "Manila", "Cebu", "Davao"],
      answer: "Manila",
      difficulty: "easy",
    },
    {
      question: "Anong simbolo ng Katipunan?",
      options: ["Kundiman", "Watawat", "Katipunan", "Kundiman"],
      answer: "Katipunan",
      difficulty: "easy",
    },
    {
      question: "Sino ang unang Pilipinong naglakbay sa buong mundo?",
      options: ["Ferdinand Magellan", "Lapu-Lapu", "Enrique of Malacca", "Jose Rizal"],
      answer: "Enrique of Malacca",
      difficulty: "easy",
    },
    {
      question: "Ano ang pangalan ng unang republika ng Pilipinas?",
      options: ["Biak-na-Bato", "Malolos", "Cavite", "Manila"],
      answer: "Biak-na-Bato",
      difficulty: "easy",
    },
    {
      question: "Saan ipinanganak si Manuel L. Quezon?",
      options: ["Baler, Aurora", "Cebu", "Manila", "Davao"],
      answer: "Baler, Aurora",
      difficulty: "easy",
    },
    {
      question: "Anong bansa ang sumakop sa Pilipinas bago ang mga Amerikano?",
      options: ["Portugal", "Britanya", "Espanya", "Hapon"],
      answer: "Espanya",
      difficulty: "easy",
    },
    {
      question: "Sino ang unang presidente ng Pilipinas?",
      options: ["Ferdinand Marcos", "Manuel L. Quezon", "Emilio Aguinaldo", "Sergio Osmeña"],
      answer: "Emilio Aguinaldo",
      difficulty: "easy",
    },
    {
      question: "Anong taon naitatag ang Unang Republika ng Pilipinas?",
      options: ["1898", "1901", "1865", "1914"],
      answer: "1898",
      difficulty: "easy",
    },
    {
      question: "Anong pangalan ng national flower ng Pilipinas?",
      options: ["Sampaguita", "Gumamela", "Dama de Noche", "Waling-Waling"],
      answer: "Sampaguita",
      difficulty: "easy",
    },
    {
      question: "Anong isla ang may pinakamataas na bundok sa Pilipinas?",
      options: ["Mindanao", "Luzon", "Palawan", "Visayas"],
      answer: "Luzon",
      difficulty: "easy",
    },
    {
      question: "Ano ang tawag sa sagisag ng isang bansa?",
      options: ["Watawat", "Bilog", "Tala", "Hibiscus"],
      answer: "Watawat",
      difficulty: "easy",
    },
    {
      question: "Saan unang nakipaglaban si Lapu-Lapu?",
      options: ["Mactan", "Manila", "Cebu", "Bohol"],
      answer: "Mactan",
      difficulty: "easy",
    },
    {
      question: "Ano ang pangalan ng pinakamataas na bundok sa Pilipinas?",
      options: ["Mount Apo", "Mount Mayon", "Mount Pulag", "Mount Banahaw"],
      answer: "Mount Apo",
      difficulty: "easy",
    },
    {
      question: "Sino ang tinaguriang ‘Ama ng Nasyonalismong Pilipino’?",
      options: ["Andres Bonifacio", "Jose Rizal", "Emilio Aguinaldo", "Sergio Osmeña"],
      answer: "Jose Rizal",
      difficulty: "easy",
    },
  
    // Medium Questions
    {
      question: "Sino ang unang babaeng Presidente ng Pilipinas?",
      options: ["Gloria Macapagal-Arroyo", "Corazon Aquino", "Imelda Marcos", "Sonia Roco"],
      answer: "Corazon Aquino",
      difficulty: "medium",
    },
    {
      question: "Anong taon unang itinatag ang Katipunan?",
      options: ["1891", "1892", "1898", "1895"],
      answer: "1892",
      difficulty: "medium",
    },
    {
      question: "Saan matatagpuan ang pinakamalaking taniman ng palay sa Pilipinas?",
      options: ["Pangasinan", "Nueva Ecija", "Ilocos Norte", "Cagayan"],
      answer: "Nueva Ecija",
      difficulty: "medium",
    },
    {
      question: "Sino ang unang nagdeklara ng kalayaan ng Pilipinas?",
      options: ["Jose Rizal", "Emilio Aguinaldo", "Andres Bonifacio", "Ferdinand Marcos"],
      answer: "Emilio Aguinaldo",
      difficulty: "medium",
    },
    {
      question: "Anong taon pinagtibay ang Saligang Batas ng Pilipinas?",
      options: ["1935", "1945", "1972", "1987"],
      answer: "1935",
      difficulty: "medium",
    },
    {
      question: "Anong taon pinirmahan ang kasunduan sa Paris na nagbigay ng kalayaan sa Pilipinas?",
      options: ["1898", "1899", "1911", "1947"],
      answer: "1898",
      difficulty: "medium",
    },
    {
      question: "Sino ang naging unang bayani na pumanaw sa Digmaang Pilipino-Amerikano?",
      options: ["Gregorio del Pilar", "Antonio Luna", "Emilio Aguinaldo", "Andres Bonifacio"],
      answer: "Antonio Luna",
      difficulty: "medium",
    },
    {
      question: "Sino ang pinakaunang Pilipinong pangulo na nahalal bilang presidente sa ilalim ng unang republika?",
      options: ["Emilio Aguinaldo", "Sergio Osmeña", "Manuel L. Quezon", "Ferdinand Marcos"],
      answer: "Emilio Aguinaldo",
      difficulty: "medium",
    },
    {
      question: "Anong taon sumik ang mga kilusang manggagawa sa Pilipinas?",
      options: ["1900", "1930", "1940", "1950"],
      answer: "1930",
      difficulty: "medium",
    },
    {
      question: "Ano ang tawag sa 'walled city' sa Manila?",
      options: ["Intramuros", "Vigan", "Cebu", "Taal"],
      answer: "Intramuros",
      difficulty: "medium",
    },
    {
      question: "Sino ang unang nagtangkang pumatay kay Ferdinand Marcos?",
      options: ["Josefa Llanes Escoda", "Benigno Aquino Jr.", "Juan Ponce Enrile", "Imelda Marcos"],
      answer: "Benigno Aquino Jr.",
      difficulty: "medium",
    },
    {
      question: "Anong bayan ang unang tinangkaan ng mga Kastila na sakupin noong 1565?",
      options: ["Cebu", "Manila", "Iloilo", "Davao"],
      answer: "Cebu",
      difficulty: "medium",
    },
    {
      question: "Anong pangalan ng unang katipunan na itinatag ni Andres Bonifacio?",
      options: ["Kundiman", "Katipunan", "Katipunan ng mga Anak ng Bayan", "Hukbalahap"],
      answer: "Katipunan",
      difficulty: "medium",
    },
    {
      question: "Anong taon ipinanganak si Emilio Aguinaldo?",
      options: ["1865", "1875", "1885", "1860"],
      answer: "1865",
      difficulty: "medium",
    },
    {
      question: "Sino ang nagbigay ng pangalan sa Pilipinas?",
      options: ["Magellan", "Ruy López de Villalobos", "Antonio de Morga", "José de la Cuadra"],
      answer: "Ruy López de Villalobos",
      difficulty: "medium",
    },
    {
      question: "Anong pangalan ng unang pangulo ng bansa na nahalal sa ilalim ng kasunduan ng batas na 1935?",
      options: ["Manuel L. Quezon", "Sergio Osmeña", "Elpidio Quirino", "Ferdinand Marcos"],
      answer: "Manuel L. Quezon",
      difficulty: "medium",
    },
    {
      question: "Saan ipinanganak si Manuel L. Quezon?",
      options: ["Baler, Aurora", "Manila", "Quezon City", "Cebu"],
      answer: "Baler, Aurora",
      difficulty: "medium",
    },
    {
      question: "Anong taon itinatag ang Malolos Republic?",
      options: ["1898", "1900", "1901", "1899"],
      answer: "1899",
      difficulty: "medium",
    },
    {
      question: "Sino ang tinaguriang ‘Ama ng Nasyonalismong Pilipino’?",
      options: ["Andres Bonifacio", "Jose Rizal", "Emilio Aguinaldo", "Sergio Osmeña"],
      answer: "Jose Rizal",
      difficulty: "medium",
    },
    {
      question: "Anong taon itinaguyod ang Digmaang Pilipino-Amerikano?",
      options: ["1899", "1901", "1900", "1941"],
      answer: "1899",
      difficulty: "medium",
    },
    {
      question: "Anong bansa ang unang nagpalit sa pangalan ng Pilipinas?",
      options: ["Britanya", "Espanya", "Hapon", "Estados Unidos"],
      answer: "Espanya",
      difficulty: "medium",
    },
    {
      question: "Ano ang pangalan ng pinakamalaking planta ng kuryente sa Pilipinas?",
      options: ["San Roque", "Sual", "Magat", "Angat"],
      answer: "San Roque",
      difficulty: "medium",
    },
    {
      question: "Ano ang tawag sa pinuno ng isang bayan o munisipalidad sa panahon ng mga Kastila?",
      options: ["Alcalde", "Kapitan", "Sargento", "Mayor"],
      answer: "Alcalde",
      difficulty: "medium",
    },
    {
      question: "Sino ang unang nanguna sa laban ng mga Pilipino laban sa mga Amerikano?",
      options: ["Emilio Aguinaldo", "Andres Bonifacio", "Antonio Luna", "Apollonio Mabini"],
      answer: "Emilio Aguinaldo",
      difficulty: "medium",
    },
    {
      question: "Anong taon ipinalabas ang Martial Law sa ilalim ni Ferdinand Marcos?",
      options: ["1972", "1971", "1965", "1981"],
      answer: "1972",
      difficulty: "medium",
    },
    {
      question: "Anong pangalan ng pinakamatandang simbahan sa Pilipinas?",
      options: ["San Agustin Church", "Quiapo Church", "Manila Cathedral", "Santo Niño Church"],
      answer: "San Agustin Church",
      difficulty: "medium",
    },
    {
      question: "Ano ang pangalan ng unang hukbo ng mga Pilipino laban sa mga Kastila?",
      options: ["Katipunan", "Hukbalahap", "Batalyon Pilipino", "Armed Forces of the Philippines"],
      answer: "Katipunan",
      difficulty: "medium",
    },
    {
      question: "Anong taon naitatag ang First Republic ng Pilipinas?",
      options: ["1899", "1900", "1901", "1911"],
      answer: "1899",
      difficulty: "medium",
    },
    {
      question: "Sino ang unang naging gobernador heneral ng Pilipinas matapos sakupin ng mga Amerikano?",
      options: ["William Howard Taft", "Arthur MacArthur", "John J. Pershing", "George Dewey"],
      answer: "William Howard Taft",
      difficulty: "medium",
    },
    {
      question: "Sino ang unang umakyat sa Mount Apo, ang pinakamataas na bundok sa Pilipinas?",
      options: ["Henry Robertson", "Pio del Pilar", "Antonio Luna", "Emilio Aguinaldo"],
      answer: "Henry Robertson",
      difficulty: "medium",
    },
    {
      question: "Anong taon nagkaroon ng 'People Power' revolution?",
      options: ["1986", "1972", "1995", "2001"],
      answer: "1986",
      difficulty: "medium",
    },
    {
      question: "Anong kasunduan ang nagbigay ng kasarinlan sa Pilipinas mula sa Estados Unidos noong 1946?",
      options: ["Treaty of Paris", "Bell Trade Act", "Tydings-McDuffie Act", "Independence Declaration"],
      answer: "Tydings-McDuffie Act",
      difficulty: "medium",
    },
    {
      question: "Sino ang naging unang lider ng Hukbalahap?",
      options: ["Luis Taruc", "Emilio Aguinaldo", "Andres Bonifacio", "Antonio Luna"],
      answer: "Luis Taruc",
      difficulty: "medium",
    },
    {
      question: "Anong taon naganap ang Bataan Death March?",
      options: ["1942", "1943", "1945", "1944"],
      answer: "1942",
      difficulty: "medium",
    },
    {
      question: "Sino ang nagpasimula ng sistemang 'Keto' sa Pilipinas?",
      options: ["Sergio Osmeña", "Manuel L. Quezon", "Jose P. Laurel", "Ferdinand Marcos"],
      answer: "Manuel L. Quezon",
      difficulty: "medium",
    },
    {
      question: "Anong kasaysayan ng Hapon ang may kinalaman sa 'Bataan Death March'?",
      options: ["Ang Digmaang Pilipino-Amerikano", "World War II", "Ang Rebolusyon ng 1896", "Ang pagbabalik ng mga Amerikano"],
      answer: "World War II",
      difficulty: "medium",
    },
    {
      question: "Anong kasunduan sa kasaysayan ng Pilipinas ang tinawag na 'Treaty of Paris'?",
      options: ["Kasunduan ng Kalayaan", "Kasunduan ng Paris", "Kasunduan ng 1898", "Kasunduan ng Bataan"],
      answer: "Kasunduan ng Paris",
      difficulty: "medium",
    },
    {
      question: "Sino ang unang Pilipinong naglakbay sa buong mundo?",
      options: ["Ferdinand Magellan", "Lapu-Lapu", "Enrique of Malacca", "Jose Rizal"],
      answer: "Enrique of Malacca",
      difficulty: "medium",
  },
  {
      question: "Anong taon naganap ang EDSA People Power Revolution?",
      options: ["1986", "1985", "1987", "1972"],
      answer: "1986",
      difficulty: "medium",
  },
  {
      question: "Ano ang tawag sa pinakamalaking pagdiriwang ng mga Pilipino sa buong mundo?",
      options: ["Sinulog", "Ati-Atihan", "Pahiyas", "Pasko"],
      answer: "Pasko",
      difficulty: "medium",
  },
  {
      question: "Sino ang naging unang babae na naging gobernador heneral ng Pilipinas?",
      options: ["Imelda Marcos", "Corazon Aquino", "Maria Orosa", "Gabriela Silang"],
      answer: "Corazon Aquino",
      difficulty: "medium",
  },
  {
      question: "Anong taon ipinanganak si Ferdinand Marcos?",
      options: ["1917", "1920", "1900", "1898"],
      answer: "1917",
      difficulty: "medium",
  },
  {
      question: "Sino ang unang naging pambansang alagad ng sining sa Pilipinas?",
      options: ["Leandro V. Locsin", "Fernando Amorsolo", "Carlos P. Romulo", "José Rizal"],
      answer: "Fernando Amorsolo",
      difficulty: "medium",
  },
  {
      question: "Anong bansa ang sumakop sa Pilipinas mula 1898 hanggang 1946?",
      options: ["Hapon", "Estados Unidos", "Espanya", "Britanya"],
      answer: "Estados Unidos",
      difficulty: "medium",
  },
  {
      question: "Ano ang tawag sa batas na nagbigay ng kalayaan sa Pilipinas mula sa Amerika?",
      options: ["Tydings-McDuffie Act", "Bell Trade Act", "Independence Act", "Treaty of Paris"],
      answer: "Tydings-McDuffie Act",
      difficulty: "medium",
  },
  {
      question: "Anong pangulo ang nagpatupad ng Martial Law sa Pilipinas noong 1972?",
      options: ["Ferdinand Marcos", "Sergio Osmeña", "Manuel L. Quezon", "Elpidio Quirino"],
      answer: "Ferdinand Marcos",
      difficulty: "medium",
  },
  {
      question: "Anong lugar ang unang nakatagpo si Ferdinand Magellan sa Pilipinas?",
      options: ["Cebu", "Leyte", "Luzon", "Mindanao"],
      answer: "Cebu",
      difficulty: "medium",
  },
  {
      question: "Sino ang unang nagtangkang pumatay kay Ferdinand Marcos?",
      options: ["Benigno Aquino Jr.", "Juan Ponce Enrile", "Imelda Marcos", "Josefa Llanes Escoda"],
      answer: "Benigno Aquino Jr.",
      difficulty: "medium",
  },
  {
      question: "Anong pangalan ng unang katipunan na itinatag ni Andres Bonifacio?",
      options: ["Katipunan", "Kundiman", "Hukbalahap", "Pagtanggol"],
      answer: "Katipunan",
      difficulty: "medium",
  },
  {
      question: "Sino ang unang Pilipinong naging gobernador heneral ng Pilipinas?",
      options: ["Ferdinand Marcos", "Manuel L. Quezon", "Emilio Aguinaldo", "Sergio Osmeña"],
      answer: "Manuel L. Quezon",
      difficulty: "medium",
  },
  {
      question: "Ano ang tawag sa pinakamalaking komunidad ng mga Pilipino sa ibang bansa?",
      options: ["OFW", "Diaspora", "Expatriates", "Balikbayan"],
      answer: "OFW",
      difficulty: "medium",
  },
  {
      question: "Anong taon naitatag ang Malolos Republic?",
      options: ["1898", "1899", "1900", "1901"],
      answer: "1899",
      difficulty: "medium",
  },
  {
      question: "Sino ang nagbigay ng pangalan sa Pilipinas?",
      options: ["Magellan", "Ruy López de Villalobos", "Antonio de Morga", "José de la Cuadra"],
      answer: "Ruy López de Villalobos",
      difficulty: "medium",
  },
  {
      question: "Sino ang naging unang bayani ng Digmaang Pilipino-Amerikano?",
      options: ["Antonio Luna", "Emilio Aguinaldo", "Andres Bonifacio", "Gregorio del Pilar"],
      answer: "Antonio Luna",
      difficulty: "medium",
  },
  {
      question: "Anong taon itinatag ang unang republikang Pilipino?",
      options: ["1899", "1900", "1901", "1905"],
      answer: "1899",
      difficulty: "medium",
  },
  {
      question: "Anong kasunduan ang nagbigay ng kasarinlan sa Pilipinas mula sa Estados Unidos?",
      options: ["Tydings-McDuffie Act", "Treaty of Paris", "Bell Trade Act", "Independence Act"],
      answer: "Tydings-McDuffie Act",
      difficulty: "medium",
  },
  {
      question: "Anong pangalan ng pinakamalaking simbahan sa Pilipinas?",
      options: ["San Agustin Church", "Quiapo Church", "Manila Cathedral", "Santo Niño Church"],
      answer: "San Agustin Church",
      difficulty: "medium",
  },
  {
      question: "Ano ang pangalan ng unang Hukbo ng mga Pilipino laban sa mga Kastila?",
      options: ["Katipunan", "Hukbalahap", "Batalyon Pilipino", "AFP"],
      answer: "Katipunan",
      difficulty: "medium",
  },
  {
      question: "Sino ang tinaguriang ‘Ama ng Nasyonalismong Pilipino’?",
      options: ["Jose Rizal", "Andres Bonifacio", "Emilio Aguinaldo", "Sergio Osmeña"],
      answer: "Jose Rizal",
      difficulty: "medium",
  },
  {
      question: "Anong taon naitatag ang Unang Republika ng Pilipinas?",
      options: ["1899", "1900", "1901", "1910"],
      answer: "1899",
      difficulty: "medium",
  },
  {
      question: "Anong taon pinagtibay ang unang Saligang Batas ng Pilipinas?",
      options: ["1935", "1945", "1972", "1987"],
      answer: "1935",
      difficulty: "medium",
  },
  {
      question: "Anong taon pinirmahan ang Kasunduan ng Paris na nagbigay ng kalayaan sa Pilipinas?",
      options: ["1898", "1900", "1910", "1945"],
      answer: "1898",
      difficulty: "medium",
  },
  {
      question: "Anong tawag sa pinuno ng isang bayan o munisipalidad sa panahon ng mga Kastila?",
      options: ["Alcalde", "Kapitan", "Sargento", "Mayor"],
      answer: "Alcalde",
      difficulty: "medium",
  },
  {
      question: "Anong pangalan ng unang katipunan na itinatag ni Andres Bonifacio?",
      options: ["Katipunan", "Hukbalahap", "Kundiman", "Anak ng Bayan"],
      answer: "Katipunan",
      difficulty: "medium",
  },
  {
      question: "Anong taon ipinanganak si Emilio Aguinaldo?",
      options: ["1865", "1875", "1860", "1880"],
      answer: "1865",
      difficulty: "medium",
  },
  {
      question: "Anong bayan ang unang tinangkaan ng mga Kastila na sakupin noong 1565?",
      options: ["Cebu", "Manila", "Davao", "Iloilo"],
      answer: "Cebu",
      difficulty: "medium",
  },
  {
      question: "Anong lugar ang pinakaunang sinakop ng mga Kastila?",
      options: ["Cebu", "Manila", "Davao", "Iloilo"],
      answer: "Cebu",
      difficulty: "medium",
  },
  {
      question: "Sino ang unang naging gobernador heneral ng Pilipinas matapos sakupin ng mga Amerikano?",
      options: ["William Howard Taft", "George Dewey", "Arthur MacArthur", "John Pershing"],
      answer: "William Howard Taft",
      difficulty: "medium",
  },
  {
      question: "Anong taon ipinanganak si Corazon Aquino?",
      options: ["1933", "1940", "1945", "1950"],
      answer: "1933",
      difficulty: "medium",
  },
  {
      question: "Anong kasunduan sa kasaysayan ng Pilipinas ang tinawag na 'Treaty of Paris'?",
      options: ["Kasunduan ng Kalayaan", "Kasunduan ng 1898", "Kasunduan ng Bataan", "Kasunduan ng Paris"],
      answer: "Kasunduan ng Paris",
      difficulty: "medium",
  },
  {
      question: "Sino ang nagpasimula ng 'Keto' diet sa Pilipinas?",
      options: ["Ferdinand Marcos", "Andres Bonifacio", "Jose Rizal", "Juan de la Cruz"],
      answer: "Juan de la Cruz",
      difficulty: "medium",
  },
  {
      question: "Anong isla ang tinatawag na 'Pearl of the Orient Seas'?",
      options: ["Palawan", "Luzon", "Cebu", "Mindanao"],
      answer: "Luzon",
      difficulty: "medium",
  },
    // Hard Questions 
    {
      question: "Sino ang unang kasapi ng Katipunan na ipinaslang ng mga Kastila?",
      options: ["Andres Bonifacio", "Jose Rizal", "Pio del Pilar", "Ladislao Diwa"],
      answer: "Ladislao Diwa",
      difficulty: "hard",
    },
    {
      question: "Saan ipinanganak si Jose Rizal?",
      options: ["Calamba, Laguna", "Manila", "Tagbilaran, Bohol", "Baguio"],
      answer: "Calamba, Laguna",
      difficulty: "hard",
    },
    {
      question: "Anong taon ipinanganak si Apolinario Mabini?",
      options: ["1864", "1871", "1884", "1858"],
      answer: "1864",
      difficulty: "hard",
    },
    {
      question: "Sino ang unang general ng Hukbalahap na pumatay kay Benigno Aquino Jr.?",
      options: ["Emilio Aguinaldo", "Fidel V. Ramos", "Luis Taruc", "Antonio Luna"],
      answer: "Luis Taruc",
      difficulty: "hard",
    },
    {
      question: "Ano ang pangalan ng unang itinaguyod na pamahalaan ng mga Amerikano sa Pilipinas?",
      options: ["Commonwealth of the Philippines", "Philippine Republic", "First Philippine Republic", "Philippine Insurrection"],
      answer: "Philippine Republic",
      difficulty: "hard",
    },
    {
      question: "Ano ang pangalan ng unang gobernador-heneral ng Pilipinas sa ilalim ng mga Amerikano?",
      options: ["William Howard Taft", "George Dewey", "Arthur MacArthur", "Henry Arnold"],
      answer: "William Howard Taft",
      difficulty: "hard",
    },
    {
      question: "Anong taon nagsimula ang pag-aalsa ng mga Pilipino laban sa mga Kastila?",
      options: ["1882", "1892", "1872", "1896"],
      answer: "1872",
      difficulty: "hard",
    },
    {
      question: "Sino ang unang nagtatag ng malawak na mga aklatan sa Pilipinas?",
      options: ["Ferdinand Marcos", "Manuel L. Quezon", "Sergio Osmeña", "Emilio Aguinaldo"],
      answer: "Manuel L. Quezon",
      difficulty: "hard",
    },
    {
      question: "Anong taon ipinanganak si Emilio Aguinaldo?",
      options: ["1865", "1858", "1875", "1859"],
      answer: "1865",
      difficulty: "hard",
    },
    {
      question: "Sino ang pangunahing tagapagtanggol ng Bataan sa panahon ng Digmaang Pilipino-Amerikano?",
      options: ["Manuel L. Quezon", "Juan Ponce Enrile", "Antonio Luna", "Fidel V. Ramos"],
      answer: "Antonio Luna",
      difficulty: "hard",
    },
    {
      question: "Sino ang pangunahing lider na nag-organisa ng mga gerilya sa mga huling taon ng World War II?",
      options: ["Benigno Aquino Jr.", "Jose Laurel", "Ramon Magsaysay", "Sergio Osmeña"],
      answer: "Jose Laurel",
      difficulty: "hard",
    },
    {
      question: "Ano ang pangalan ng unang kongreso ng mga Pilipino na itinaguyod ng mga Amerikano?",
      options: ["Philippine Assembly", "National Congress", "Malolos Congress", "Philippine Congress"],
      answer: "Philippine Assembly",
      difficulty: "hard",
    },
    {
      question: "Saan ipinanganak si Andres Bonifacio?",
      options: ["Tondo, Manila", "Cavite", "Calamba, Laguna", "Baler, Aurora"],
      answer: "Tondo, Manila",
      difficulty: "hard",
    },
    {
      question: "Anong taon naganap ang malawakang digmaan ng Pilipino laban sa mga Amerikano?",
      options: ["1899", "1901", "1911", "1900"],
      answer: "1899",
      difficulty: "hard",
    },
    {
      question: "Ano ang pangalan ng unang pangulo ng unang republika ng Pilipinas?",
      options: ["Emilio Aguinaldo", "Sergio Osmeña", "Manuel Quezon", "Ferdinand Marcos"],
      answer: "Emilio Aguinaldo",
      difficulty: "hard",
    },
    {
      question: "Ano ang tawag sa kasunduan ng mga Pilipino at Amerikano na nilagdaan pagkatapos ng Digmaang Pilipino-Amerikano?",
      options: ["Treaty of Paris", "Bell Trade Act", "Tydings-McDuffie Act", "Philippine Bill"],
      answer: "Treaty of Paris",
      difficulty: "hard",
    },
    {
      question: "Sino ang nagtatag ng unang republika sa Pilipinas?",
      options: ["Andres Bonifacio", "Sergio Osmeña", "Manuel L. Quezon", "Emilio Aguinaldo"],
      answer: "Emilio Aguinaldo",
      difficulty: "hard",
    },
    {
      question: "Saan ipinanganak si Ferdinand Marcos?",
      options: ["Sarrat, Ilocos Norte", "Vigan, Ilocos Sur", "Quezon City", "Baguio"],
      answer: "Sarrat, Ilocos Norte",
      difficulty: "hard",
    },
    {
      question: "Anong taon itinaguyod ang rebolusyong Pilipino laban sa mga Kastila?",
      options: ["1898", "1897", "1896", "1899"],
      answer: "1896",
      difficulty: "hard",
    },
    {
      question: "Ano ang tawag sa kasunduan na itinaguyod ni Pangulong Manuel L. Quezon upang makamit ang kalayaan ng Pilipinas?",
      options: ["Tydings-McDuffie Act", "Treaty of Paris", "Philippine Independence Act", "Bell Trade Act"],
      answer: "Tydings-McDuffie Act",
      difficulty: "hard",
    },
    {
      question: "Sino ang sumunod kay Emilio Aguinaldo bilang pangulo ng Pilipinas sa ilalim ng Malolos Republic?",
      options: ["Fidel V. Ramos", "Sergio Osmeña", "Antonio Luna", "Pedro Paterno"],
      answer: "Pedro Paterno",
      difficulty: "hard",
    },
    {
      question: "Sino ang nagpasimula ng mga repormang agraryo sa Pilipinas?",
      options: ["Manuel Quezon", "Ferdinand Marcos", "Jose Laurel", "Carlos P. Garcia"],
      answer: "Ferdinand Marcos",
      difficulty: "hard",
    },
    {
      question: "Ano ang pangalan ng pinakamalaking laban sa mga Pilipino sa panahon ng Digmaang Pilipino-Amerikano?",
      options: ["Battle of Manila", "Battle of Bataan", "Battle of Tirad Pass", "Battle of Balintawak"],
      answer: "Battle of Tirad Pass",
      difficulty: "hard",
    },
    {
      question: "Sino ang naging pinuno ng Katipunan pagkatapos ng kamatayan ni Andres Bonifacio?",
      options: ["Emilio Aguinaldo", "Jose Rizal", "Antonio Luna", "Apollonio Mabini"],
      answer: "Emilio Aguinaldo",
      difficulty: "hard",
    },
    {
      question: "Anong taon unang ipinatupad ang Commonwealth ng Pilipinas?",
      options: ["1935", "1925", "1941", "1946"],
      answer: "1935",
      difficulty: "hard",
    },
    {
      question: "Ano ang tawag sa unang kasunduan sa pagitan ng mga Pilipino at mga Amerikano na nagbigay daan sa kalayaan ng Pilipinas?",
      options: ["Treaty of Paris", "Philippine Bill", "Tydings-McDuffie Act", "Bates Agreement"],
      answer: "Bates Agreement",
      difficulty: "hard",
    },
    {
      question: "Sino ang unang ginugol ang kanyang buhay sa pagpapalaganap ng nasyonalismong Pilipino?",
      options: ["Andres Bonifacio", "Emilio Aguinaldo", "Antonio Luna", "Jose Rizal"],
      answer: "Jose Rizal",
      difficulty: "hard",
    },
    {
      question: "Saan nangyari ang ‘Himagsikang 1896’?",
      options: ["Cavite", "Manila", "Baguio", "Iloilo"],
      answer: "Cavite",
      difficulty: "hard",
    },
    {
      question: "Anong pangulo ang may 'People Power' na pinangunahan ni Corazon Aquino?",
      options: ["Ferdinand Marcos", "Jose P. Laurel", "Carlos P. Garcia", "Elpidio Quirino"],
      answer: "Ferdinand Marcos",
      difficulty: "hard",
    },
    {
      question: "Sino ang unang bayani na ipinadala sa exilio sa Hong Kong?",
      options: ["Jose Rizal", "Andres Bonifacio", "Emilio Aguinaldo", "Antonio Luna"],
      answer: "Andres Bonifacio",
      difficulty: "hard",
    },
    {
      question: "Ano ang tawag sa dokumento na nagpapakita ng mga plano at aksyon upang mapanatili ang soberanya ng bansa laban sa pananakop?",
      options: ["Bates Agreement", "Philippine Independence Act", "Treaty of Paris", "Malolos Constitution"],
      answer: "Malolos Constitution",
      difficulty: "hard",
    },
    {
      question: "Anong taon naganap ang Battle of Manila Bay?",
      options: ["1898", "1901", "1941", "1930"],
      answer: "1898",
      difficulty: "hard",
    },
    {
      question: "Anong taon namatay si Andres Bonifacio?",
      options: ["1897", "1901", "1895", "1899"],
      answer: "1897",
      difficulty: "hard",
    },
    {
      question: "Saan naganap ang unang laban ng Katipunan?",
      options: ["Balintawak", "Cavite", "Malolos", "Bagumbayan"],
      answer: "Balintawak",
      difficulty: "hard",
    },
    {
      question: "Anong taon ipinanganak si Pangulong Sergio Osmeña?",
      options: ["1878", "1889", "1887", "1892"],
      answer: "1878",
      difficulty: "hard",
    },
    {
      question: "Sino ang pangulo ng unang republika ng Pilipinas noong panahon ng himagsikan?",
      options: ["Emilio Aguinaldo", "Andres Bonifacio", "Manuel L. Quezon", "Sergio Osmeña"],
      answer: "Emilio Aguinaldo",
      difficulty: "hard",
    },
    {
      question: "Anong taon unang itinaguyod ang Malolos Constitution?",
      options: ["1899", "1917", "1947", "1918"],
      answer: "1899",
      difficulty: "hard",
    },
    {
      question: "Saan unang itinaas ang watawat ng Pilipinas?",
      options: ["Kawit, Cavite", "Malolos, Bulacan", "Tondo, Manila", "Bagumbayan, Manila"],
      answer: "Kawit, Cavite",
      difficulty: "hard",
    },
    {
      question: "Anong kilusan ang pinasimulan ni Marcelo H. del Pilar?",
      options: ["La Solidaridad", "Katipunan", "Propaganda Movement", "Reform Movement"],
      answer: "Propaganda Movement",
      difficulty: "hard",
    },
    {
      question: "Sino ang pinuno ng unang Labanan sa Pasong Tirad?",
      options: ["Gregorio del Pilar", "Antonio Luna", "Emilio Aguinaldo", "Manuel Tinio"],
      answer: "Gregorio del Pilar",
      difficulty: "hard",
    },
    {
      question: "Ano ang pangalan ng unang unibersidad sa Pilipinas?",
      options: ["University of Santo Tomas", "Ateneo de Manila", "San Juan de Letran", "University of the Philippines"],
      answer: "University of Santo Tomas",
      difficulty: "hard",
    },
    {
      question: "Anong taon naipasa ang Batas Jones?",
      options: ["1916", "1925", "1935", "1940"],
      answer: "1916",
      difficulty: "hard",
    },
    {
      question: "Sino ang unang Pilipino na naging miyembro ng Spanish Cortes?",
      options: ["Pedro Paterno", "Jose Rizal", "Graciano Lopez Jaena", "Manuel Quezon"],
      answer: "Pedro Paterno",
      difficulty: "hard",
    },
    {
      question: "Sino ang pinuno ng 'Makapili' noong panahon ng Hapon?",
      options: ["Benigno Ramos", "Jose P. Laurel", "Manuel Roxas", "Claro M. Recto"],
      answer: "Benigno Ramos",
      difficulty: "hard",
    },
    {
      question: "Ano ang tunay na pangalan ni Francisco Balagtas?",
      options: ["Francisco Baltazar", "Francisco Mercado", "Francisco Delgado", "Francisco Mabini"],
      answer: "Francisco Baltazar",
      difficulty: "hard",
    },
    {
      question: "Anong bansa ang tumulong sa Pilipinas sa kalayaan laban sa mga Kastila?",
      options: ["United States", "Japan", "China", "Mexico"],
      answer: "United States",
      difficulty: "hard",
    },
    {
      question: "Anong kasunduan ang nagtapos sa pananakop ng Espanya sa Pilipinas?",
      options: ["Treaty of Paris", "Treaty of Tordesillas", "Bates Treaty", "Tydings-McDuffie Act"],
      answer: "Treaty of Paris",
      difficulty: "hard",
    },
    {
      question: "Ano ang kilala bilang ‘Cry of Pugad Lawin’?",
      options: ["Simula ng Rebolusyon", "Kasunduan ng Biak-na-Bato", "Pagbitay kay Rizal", "Pagpapahayag ng Kalayaan"],
      answer: "Simula ng Rebolusyon",
      difficulty: "hard",
    },
    {
      question: "Ano ang tunay na pangalan ni Apolinario Mabini?",
      options: ["Apolinario Mariño", "Apolinario Manalo", "Apolinario Morales", "Apolinario de la Cruz"],
      answer: "Apolinario Mariño",
      difficulty: "hard",
    },
    {
      question: "Ano ang naging tawag sa mga Pilipino na lumaban sa mga Kastila?",
      options: ["Insulares", "Ilustrados", "Indios", "Revolucionarios"],
      answer: "Revolucionarios",
      difficulty: "hard",
    },
    {
      question: "Ano ang naging epekto ng Batas Tydings-McDuffie sa Pilipinas?",
      options: ["Kalayaan mula sa Estados Unidos", "Pagpasok ng mga Amerikano sa Pilipinas", "Pagsisimula ng pananakop ng Hapon", "Pagkakaroon ng sariling saligang batas"],
      answer: "Kalayaan mula sa Estados Unidos",
      difficulty: "hard",
    },
    {
      question: "Sino ang huling gobernador-heneral ng Espanya sa Pilipinas?",
      options: ["Basilio Agustin", "Diego de los Rios", "Rafael Izquierdo", "Camilo Polavieja"],
      answer: "Diego de los Rios",
      difficulty: "hard",
    },
    {
      question: "Ano ang tawag sa sistemang pampolitika ng mga Espanyol na nagtatag ng mga pueblo?",
      options: ["Reduccion", "Encomienda", "Alcaldia", "Indulto"],
      answer: "Reduccion",
      difficulty: "hard",
    },
    {
      question: "Ano ang pangunahing layunin ng Kasunduan ng Biak-na-Bato?",
      options: ["Pagtigil ng Rebolusyon", "Pagkakaroon ng Kalayaan", "Pagbawi ng Bataan", "Pagtatag ng Republika"],
      answer: "Pagtigil ng Rebolusyon",
      difficulty: "hard",
    },
    {
      question: "Sino ang pinuno ng Kilusang Propaganda?",
      options: ["Jose Rizal", "Graciano Lopez Jaena", "Marcelo H. del Pilar", "Antonio Luna"],
      answer: "Marcelo H. del Pilar",
      difficulty: "hard",
    },
    {
      question: "Anong bayan sa Bulacan ang naging kabisera ng unang republika ng Pilipinas?",
      options: ["Malolos", "Plaridel", "San Miguel", "Guiguinto"],
      answer: "Malolos",
      difficulty: "hard",
    },
    {
      question: "Sino ang unang babaeng Pilipina na naging gobernador ng isang probinsya?",
      options: ["Carmen Planas", "Gabriela Silang", "Corazon Aquino", "Josefa Llanes Escoda"],
      answer: "Carmen Planas",
      difficulty: "hard",
    },
    {
      question: "Anong taon naipasa ang Hare-Hawes-Cutting Act?",
      options: ["1933", "1946", "1935", "1927"],
      answer: "1933",
      difficulty: "hard",
    },
    {
      question: "Saan idinaos ang unang sesyon ng Philippine Assembly noong 1907?",
      options: ["Manila", "Malolos", "Cavite", "Iloilo"],
      answer: "Manila",
      difficulty: "hard",
    },
    {
      question: "Ano ang tawag sa mga Pilipino na naglingkod sa gobyerno ng Espanya noong kolonyal na panahon?",
      options: ["Ilustrados", "Indios", "Principalia", "Ladrones"],
      answer: "Principalia",
      difficulty: "hard",
    },
    {
      question: "Sino ang unang Pilipinong abogado?",
      options: ["Graciano Lopez Jaena", "Felix Resurreccion Hidalgo", "Jose Burgos", "Antonio Luna"],
      answer: "Jose Burgos",
      difficulty: "hard",
    },
    {
      question: "Ano ang tawag sa pinakamalaking barko ng mga Espanyol na ginamit sa Galleon Trade?",
      options: ["Galleon", "Nao", "Caravel", "Frigate"],
      answer: "Nao",
      difficulty: "hard",
    },
    {
      question: "Sino ang sumulat ng aklat na *Fray Botod*?",
      options: ["Graciano Lopez Jaena", "Jose Rizal", "Marcelo H. del Pilar", "Juan Luna"],
      answer: "Graciano Lopez Jaena",
      difficulty: "hard",
    },
    {
      question: "Anong batas ang nagbigay ng karapatan sa mga kababaihan sa Pilipinas na bumoto?",
      options: ["Batas Pambansa Blg. 34", "Women Suffrage Law", "Tydings-McDuffie Act", "Jones Law"],
      answer: "Women Suffrage Law",
      difficulty: "hard",
    },
    {
      question: "Sino ang unang Pilipino na tumayo sa entablado ng Spanish Cortes?",
      options: ["Pedro Paterno", "Jose Rizal", "Gregorio Sancianco", "Manuel L. Quezon"],
      answer: "Gregorio Sancianco",
      difficulty: "hard",
    },
    {
      question: "Ano ang paboritong sandata ng mga gerilya noong World War II?",
      options: ["Itak", "Baril", "Granada", "Arnis"],
      answer: "Itak",
      difficulty: "hard",
    },
    {
      question: "Anong dekada naitatag ang KKK o Katipunan?",
      options: ["1890s", "1880s", "1870s", "1860s"],
      answer: "1890s",
      difficulty: "hard",
    },
  ];
    
  